In [20]:
import numpy as np
x=np.ones((5,1))
x

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [22]:
y=np.random.randn(1,7)
print(y)
np.shape(x-y)

[[-1.27840681 -0.2333407  -2.52537727  1.24369932  0.53362031  0.64716564
   0.04822687]]


(5, 7)

In [23]:
array = np.array([3,1,9,4])
sorted_indices = np.argsort(array)

In [24]:
print(sorted_indices)
print(array)

[1 0 3 2]
[3 1 9 4]


In [25]:
print(sorted_indices[::-1])

[2 3 0 1]


In [30]:
y=np.array([1,2,2,3,4,5,5,5,6,7,7,7,7,8,8,9])
x=np.array([0,4,7])
type(y[x])

numpy.ndarray

In [32]:
unique, counts = np.unique(y, return_counts=True) 

In [41]:
print(unique)
print(counts)

[1 2 3 4 5 6 7 8 9]
[1 2 1 1 3 1 4 2 1]


In [42]:
np.argmax(counts)

6

In [52]:
dist=np.zeros((10,200))

x=np.random.randn(10,5)
y=np.ones((200,5))
#for i in range(len(x)):
#dist[i,:]=x[i]-y #5*1 -200*5
(np.sum(x[1]-y, axis=1)).shape    

(200,)

In [27]:
import numpy as np
x=np.array([[1,5,3,4,7],[2,3,4,5,6]])
y=np.zeros(x.shape)+np.random.randn(2,5)
#type(y)
#np.random.randn(2,5)
y
#print(np.max(y,np.zeros(x.shape)))

array([[ 0.12614993, -0.14442189, -1.57453107, -0.30549787,  0.0840377 ],
       [-0.34044255,  0.95819568,  0.68730667,  0.53532749, -0.263631  ]])

In [28]:
np.zeros(x.shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
str(100+2) + "%"

'102%'

In [10]:
import numpy as np
x=np.random.randn(3,5)
y=np.ones((3,1))

print(x)
print(y)
x+y

[[-1.25726584 -1.25975325 -0.30031834  0.10211343  0.44988061]
 [ 0.17497231  0.41386409  1.63681853  0.04597405  1.39583349]
 [ 1.25919201 -0.72005895  0.25142977  0.30253116  0.70208907]]
[[1.]
 [1.]
 [1.]]


array([[-0.25726584, -0.25975325,  0.69968166,  1.10211343,  1.44988061],
       [ 1.17497231,  1.41386409,  2.63681853,  1.04597405,  2.39583349],
       [ 2.25919201,  0.27994105,  1.25142977,  1.30253116,  1.70208907]])

In [12]:
z={}
z[1]=2
z

{1: 2}